export const BASE_API = "http://3.17.255.202:8009/transporter/api/v1/user"
export const LOGGED_IN_STATE = "LOGGED_IN_STATE"
export const ACCESS_TOKEN = "ACCESS_TOKEN_CLIENT"
export const PHONE_NUMBER = "PHONE_NUMBER"
export const USER_PROFILE = "USER_PROFILE"
export const INIT_DATA = "INIT_DATA"